---
- name: cron - dconf
  cron:
    user: "{{ user }}"
    name: Daily dconf export
    job: "{{ home_dir }}/.dconf/bin/dump"
    hour: 16
    minute: 0
    state: present

- name: cron - duplicity
  cron:
    user: "{{ user }}"
    name: Daily duplicity backup
    job: "{{ home_dir }}/.duplicity/bin/backup"
    hour: 16
    minute: 30
    state: present
