---
- name: dotfiles
  become: no
  template:
    src="{{ ansible_dir }}/user/files/dotfiles/{{ item }}"
    dest="{{ home_dir}}/.{{ item }}"
  with_items:
    - asoundrc
    - dircolors
    - gemrc
    - ghci
    - gitconfig
    - gitignore
    - irbrc
    - npmrc
    - railsrc
    - rspec
    - sqliterc
    - xsessionrc
    - zshenv
    - zshrc
  tags: dotfiles
