---
  # The list is in the backup. If the list doesn't exist the backup has not been
  # restored
- name: duplicity - file list exists
  stat: path="{{ home_dir }}/.duplicity/lists/inclusion-list"
  register: duplicity_list

- name: duplicity - download
  become: no
  git:
    repo=https://github.com/rpbaptist/duplicity-home-backup.git
    dest="{{ home_dir }}/.duplicity"
    update=yes

- name: duplicity - variables
  become: no
  copy:
    src: "{{ ansible_dir }}/user/files/duplicity"
    dest: "{{ home_dir }}/.duplicity/vars/export"
    mode: 0600

- name: duplicity - restore
  become: no
  shell:
    chdir="{{ home_dir }}/.duplicity/"
    "bin/restore-all {{ home_dir }}"
  when: not duplicity_list.stat.exists
