---
  # The list is in the backup. If the list doesn't exist the backup has not been
  # restored
- name: duplicity - file list exists
  stat: path="{{ home_dir }}/.duplicity/lists/inclusion-list"
  register: duplicity_list

- name: duplicity - download
  become: no
  git:
    repo=https://github.com/rpbaptist/duplicity-home-backup.git
    dest="{{ home_dir }}/.duplicity"
    update=no

- name: duplicity - credentials
  become: no
  lineinfile:
    dest: "{{ home_dir }}/.duplicity/vars/export"
    state: present
    line: "{{ item }}"
  with_items:
    - "export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}"
    - "export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}"
    - "export S3_DUPLICITY_DIR={{ s3_duplicity_dir }}"
    - "export PASSPHRASE={{ passphrase }}"

- name: duplicity - restore
  become: no
  command:
    chdir="{{ home_dir }}/.duplicity/"
    bin/restore-all --force "/"
  when: not duplicity_list.stat.exists