---
- name: Hub - check existence
  stat: path="{{ home_dir }}/.local/bin/hub"
  register: hub

- name: Hub - unarchive
  become: no
  unarchive:
    src=https://github.com/github/hub/releases/download/v2.3.0-pre8/hub-linux-amd64-2.3.0-pre8.tgz
    dest="{{ home_dir }}/code/apps"
    copy=no
  when: not hub.stat.exists

- name: Hub - rename
  become: no
  command: mv {{ home_dir }}/code/apps/hub-linux-amd64-2.3.0-pre8 {{ home_dir }}/code/apps/hub
  when: not hub.stat.exists

- name: Hub - copy zsh completions
  become: no
  copy:
    src="{{ home_dir }}/code/apps/hub/etc/hub.zsh_completion"
    dest="{{ home_dir }}/.zsh/completions/_hub"
    mode=0775
  when: not hub.stat.exists

- name: Hub - copy binary
  become: no
  copy:
    src="{{ home_dir }}/code/apps/hub/bin/hub"
    dest="{{ home_dir }}/.local/bin/hub"
    mode=0755
  when: not hub.stat.exists
