---
- include: profile.yml
- include: duplicity.yml
- include: dotfiles.yml
- include: hub.yml
- include: ruby.yml
- include: node.yml
- include: lein.yml
- include: ngrok.yml
- include: docker.yml
- include: trash.yml
