---
- name: NVM - exists
  stat: path={{ home_dir}}/.nvm/nvm.sh
  register: nvm

- name: NVM - download
  become: no
  get_url:
    url=https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh
    dest={{ download_dir }}/nvm-install.sh
    mode=0755
  when: not nvm.stat.exists

- name: NVM - install
  become: no
  shell: "{{ download_dir }}/nvm-install.sh"
  when: not nvm.stat.exists

- name: Node - install
  become: no
  shell: "{{ home_dir}}/.nvm/nvm.sh {{ item }}"
  with_items:
    - install node
    - use node
  when: not nvm.stat.exists
