---
- name: Oh My Zsh
  become: no
  git:
    repo=https://github.com/rpbaptist/oh-my-zsh.git
    dest="{{ home_dir }}/.oh-my-zsh"
    update=no

- name: Redshift - configuration
  become: no
  template:
    src="{{ ansible_dir }}/user/files/config/redshift.conf"
    dest="{{ home_dir}}/.config/redshift.conf"

- name: hosts
  become: no
  git:
    repo=https://github.com/StevenBlack/hosts.git
    dest="{{ home_dir }}/code/apps/hosts"
    update=no

- name: libinput gestures
  become: no
  git:
    repo=http://github.com/bulletmark/libinput-gestures.git
    dest="{{ home_dir }}/code/apps/libinput-gestures"
    update=no

- name: Libinput gestures - configuration
  become: no
  template:
    src="{{ ansible_dir }}/user/files/config/libinput-gestures.conf"
    dest="{{ home_dir}}/.config/libinput-gestures.conf"

- name: Terminix - scheme
  become: no
  template:
    src="{{ ansible_dir }}/user/files/themes/terminix.json"
    dest="{{ home_dir}}/.config/terminix/schemes/richard.json"
