---
- name: Oh My Zsh
  become: no
  git:
    repo=https://github.com/rpbaptist/oh-my-zsh.git
    dest="{{ home_dir }}/.oh-my-zsh"
    update=no

- name: Use ZSH
  shell: chsh -s /usr/bin/zsh

- name: Papirus icons
  become: no
  command:
    wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install-papirus-home-gtk.sh | sh
