---
- name: rbenv
  become: no
  git:
    repo=https://github.com/rbenv/rbenv.git
    dest="{{ home_dir }}/.rbenv"
    update=no

- name: ruby-build
  become: no
  git:
    repo=https://github.com/rbenv/ruby-build.git
    dest="{{ home_dir }}/.rbenv/plugins/ruby-build"
    update=no

- name: rbenv-gem-rehash
  become: no
  git:
    repo=https://github.com/rbenv/rbenv-gem-rehash.git
    dest="{{ home_dir }}/.rbenv/plugins/rbenv-gem-rehash"
    update=no

- name: rbenv-vars
  become: no
  git:
    repo=https://github.com/rbenv/rbenv-vars.git
    dest="{{ home_dir }}/.rbenv/plugins/rbenv-vars"
    update=no

- name: Ruby - check if installed
  stat: path="{{ home_dir }}/.rbenv/shims/ruby"
  register: ruby

- name: Ruby setup
  become: no
  command: "{{ item }}"
  with_items:
    - rbenv install 2.1.8
    - rbenv install 2.2.4
    - rbenv install 2.3.0
    - rbenv global 2.3.0
    - gem install bundler
    - gem install rails
    - rbenv rehash
  when: not ruby.stat.exists
