---
- name: Oh My Zsh
  become: no
  git:
    repo=https://github.com/rpbaptist/oh-my-zsh.git
    dest="{{ home_dir }}/.oh-my-zsh"
    update=no

- name: Use ZSH
  lineinfile:
    dest: /etc/passwd
    regexp: '^richard:x:1000:1000:richard,,,:/home/richard:/bin/bash$'
    line: richard:x:1000:1000:richard,,,:/home/richard:/bin/zsh
    state: present
