---
- name: arc-theme - exists
  stat: path=/usr/share/themes/Arc
  register: arc-theme

- name: arc-theme - download
  become: no
  git:
    repo=https://github.com/horst3180/arc-theme.git
    dest="{{ home_dir }}/code/apps/arc-theme"
    update=no

- name: arc-theme - install
  command:
    chdir="{{ home_dir }}/code/apps/arc-theme/"
    "{{ item }}"
  with_items:
    - ./autogen.sh --prefix=/usr
    - make install
    - sed -i.orig 's/white/#d3dae3/g' /usr/share/themes/Arc-Dark/cinnamon/cinnamon.css
  when: not arc-theme.stat.exists
