---
- name: Create directories in home
  become: no
  file:
    path="{{ home_dir }}/{{ item }}"
    state=directory
    mode=0775
  with_items:
    - .local/bin
    - .zsh/completions
    - code/apps
    - Desktop
    - Downloads
    - Pictures
    - Sync
    - Videos

- name: Create system directories
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - /etc/X11/xorg.conf.d
    - /usr/share/backgrounds
