---
- name: Create directories in home
  become: no
  file:
    path="{{ home_dir }}/{{ item }}"
    state=directory
  with_items:
    - Downloads
    - Dropbox/Sublime/Packages
    - Dropbox/Sublime/Installed Packages
