---
- name: Create directories in home
  become: no
  file:
    path="{{ home_dir }}/{{ item }}"
    state=directory
  with_items:
    - Downloads
    - Dropbox/Sublime/Packages
    - Dropbox/Sublime/Installed Packages

- name: Create system directories
  file:
    path=/etc/X11/xorg.conf.d
    state=directory
