---
- name: Create directories in home
  become: no
  file:
    path="{{ home_dir }}/{{ item }}"
    state=directory
  with_items:
    - Downloads
    - Dropbox/Sublime/Packages
    - Dropbox/Sublime/Installed Packages
    - .config/terminix/schemes

- name: Create system directories
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - /etc/X11/xorg.conf.d
    - /usr/share/backgrounds
