---
- name: grub - config
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$',
      line: GRUB_CMDLINE_LINUX_DEFAULT="pcie_aspm=force i915.preliminary_hw_support=0"
    }
    - {
      regexp: '^GRUB_TIMEOUT=\d*$',
      line: GRUB_TIMEOUT=0
    }
  tags: grub

- name: grub - update
  command: update-grub
  tags: grub
