---
- name: hosts - download
  become: no
  git:
    repo=https://github.com/StevenBlack/hosts.git
    dest="{{ home_dir }}/code/apps/hosts"
    update=no
  notify: hosts - update

- name: hosts - update
  command:
    chdir="{{ home_dir }}/code/apps/hosts/"
    python3 /updateHostFile.py -a -r --extensions porn
