---
- name: i3 - download repo
  become: no
  git:
    repo: https://www.github.com/Airblader/i3
    dest: "{{ home_dir }}/code/apps/i3-gaps"
    update: yes
  tags: i3

- name: i3 - compile
  become: no
  shell: "{{ item }}"
  args:
    chdir: "{{ home_dir }}/code/apps/i3-gaps"
  with_items:
    - autoreconf --force --install
    - rm -rf build/
    - mkdir -p build && cd build/
    - ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    - make
  tags: i3

- name: i3 - install
  shell: make install
  args:
    chdir: "{{ home_dir }}/code/apps/i3-gaps"
  tags: i3
