---
- name: Papirus icons - change tray color
  replace:
    dest: /usr/share/themes/Arc-Dark/cinnamon/cinnamon.css
    regexp: 'white'
    replace: '#d3dae3'

- name: Papirus icons - change tray icons
  shell: sudo hardcode-tray --conversion-tool Inkscape --dark-theme Papirus --size 24 --apply
