---
- name: KeepassX - check existence
  stat: path=/usr/local/bin/keepassx
  register: keepassx

- name: KeepassX - Clone repo
  become: no
  git:
    repo=https://github.com/keepassx/keepassx.git
    dest="{{ home_dir }}/code/apps/keepassx"
    force=yes
    version=2.0.2
  when: not keepassx.stat.exists

- name: KeepassX - make directory
  become: no
  file:
    path="{{ home_dir }}/code/apps/keepassx/build"
    state=directory
    mode=0775

- name: KeepassX - build and install
  command: '"{{ item }}" chdir="{{ home_dir }}/code/apps/keepassx/build"'
  with_items:
    - cmake ..
    - make
    - make install
  when: not keepassx.stat.exists
