---
- name: Keybase - download
  get_url:
    url=https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb
    dest="{{ download_dir }}/keybase-latest-amd64.deb"

- name: Keybase - install
  apt:
    deb: "{{ download_dir }}/keybase-latest-amd64.deb"
    state: present
