---
- name: libinput-gestures - exists
  stat: path=/usr/bin/libinput-gestures
  register: libinput_gestures

- name: libinput gestures - download
  become: no
  git:
    repo=http://github.com/bulletmark/libinput-gestures.git
    dest="{{ home_dir }}/code/apps/libinput-gestures"
    update=no

- name: libinput-gestures - install
  command:
    chdir="{{ home_dir }}/code/apps/libinput-gestures/"
    make install
  when: not libinput_gestures.stat.exists

- name: libinput gestures - configuration
  become: no
  template:
    src="{{ ansible_dir }}/user/files/config/libinput-gestures.conf"
    dest="{{ home_dir}}/.config/libinput-gestures.conf"
