---
- include: ppa.yml
- include: packages-remove.yml
- include: packages-install.yml
- include: keepassx.yml
- include: sublime.yml
- include: slack.yml
# - include: shell.yml
# - include: databases.yml
