---
- name: openzone - download exists
  become: no
  stat:
    path: "{{ download_dir }}/OpenZone"
  register: openzone_cursor_download

- name: openzone - download
  become: no
  unarchive:
    src: "https://dl.opendesktop.org/api/files/download/id/1462316428/111343-OpenZone-{{ openzone_version }}.tar.xz"
    dest: "{{ download_dir}}"
    copy: no
  when: not openzone_cursor_download.stat.exists

- name: openzone - on system
  become: no
  stat:
    path: /usr/share/icons/OpenZone_Ice
  register: openzone_cursor_files

- name: openzone - copy
  unarchive:
    src: "{{ download_dir }}/OpenZone/OpenZone_Ice-{{ openzone_version }}.tar.xz"
    dest: /usr/share/icons/
  when: not openzone_cursor_files.stat.exists

- name: openzone - configure
  lineinfile:
    dest: /usr/share/icons/OpenZone_Ice/index.theme
    line: Inherits=OpenZone_Ice
    state: present

- name: openzone - add
  command: >
    update-alternatives
    --install /usr/share/icons/default/index.theme
    x-cursor-theme /usr/share/icons/OpenZone_Ice/index.theme 80

- name: openzone - set
  command: >
    update-alternatives
    --set x-cursor-theme /usr/share/icons/OpenZone_Ice/index.theme
