---
- name: openvpn - certificates
  become: no
  unarchive:
    src: http://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: "{{ home_dir }}/.openvpn"
    copy: no
    creates: "{{ home_dir }}/.openvpn"

- name: openvpn - coonfiguration
  copy:
    src: "{{ ansible_dir }}/system/files/vpn_pia"
    dest: /etc/NetworkManager/system-connections/VPN-Private-Internet-Access
    mode: 0600
