---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=latest
  with_items:
    - ansible
    - build-essential
    - cinnamon-desktop-environment
    - cmake
    - dropbox
    - folder-color-nemo
    - gconf-editor
    - git
    - gnome-icon-theme-full
    - google-chrome-stable
    - gpaste
    - guvcview
    - heroku-toolbelt
    - httpie
    - leafpad
    - libcurl4-openssl-dev
    - libffi-dev
    - libgcrypt11-dev
    - libqt4-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - python-gpgme
    - python-nemo
    - python-software-properties
    - redshift
    - redshift-gtk
    - shutter
    - skype
    - sqlite3
    - touchegg
    - uvcdynctrl
    - vivacious-colors
    - vivacious-folder-colors-addon
    - vlc
    - xclip
    - zlib1g-dev
    - zsh

- name: Apps | Remove packages which are installed by default
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - ace-of-penguins
    - aisleriot
    - brasero
    - cheese
    - empathy
    - five-or-more
    - four-in-a-row
    - gbrainy
    - gedit
    - gnome-chess
    - gnome-games-common
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-nibbles
    - gnome-robots
    - gnome-screenshot
    - gnome-sudoku
    - gnome-tetravex
    - gnomine
    - hamster-applet
    - hamster-indicator
    - iagno
    - lightsoff
    - mahjongg
    - quadrapassel
    - sound-juicer
    - swell-foop
    - tali
    - thunderbird
    - totem
    - totem-plugins
    - unity-webapps-common
    - webbrowser-app
    - xboard
    - xterm
