---
- name: Papirus icons - exists
  become: no
  stat:
    path: /usr/share/icons/Papirus-Dark
  register: papirus_icons

- name: Papirus icons - download
  become: no
  get_url:
    url: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install-papirus-root.sh
    dest: "{{ download_dir }}"
    mode: 0755
  when: not papirus_icons.stat.exists

- name: Papirus icons - install
  shell: "{{ download_dir }}/install-papirus-root.sh"
  when: not papirus_icons.stat.exists

- name: Papirus icons - change tray color
  replace:
    dest: /usr/share/themes/Arc-Dark/cinnamon/cinnamon.css
    regexp: 'white'
    replace: '#d3dae3'

- name: hardcode-tray - download
  become: no
  git:
    repo: git@github.com:bil-elmoussaoui/Hardcode-Tray.git
    dest: "{{ home_dir }}/code/apps/hardcode-tray"
    update: yes

- name: hardcode-tray - install
  shell: "{{ home_dir }}/code/apps/hardcode-tray/install.sh"

- name: Papirus icons - change tray icons
  shell: hardcode-tray --conversion-tool Inkscape --dark-theme Papirus --size 24
