---
- name: tlp - start
  command: tlp start

- name: tlp - configure
  lineinfile:
    dest: /etc/default/tlp
    regexp: 'DEVICES_TO_DISABLE_ON_STARTUP="bluetooth wifi wwan"'
    line: DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
    state: present

- name: ssd - swappiness
  lineinfile:
    dest: /proc/sys/vm/swappiness
    line: vm.swappiness=1
    state: present