---
- name: PPA keys - Add keys for repositories
  apt_key: url={{ item }} state=present
  with_items:
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://toolbelt.heroku.com/apt/release.key
    - https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: PPA keys - add with id
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }} state=present
  with_items:
    # Haskell
    - { keyserver: 'hkp://keyserver.ubuntu.com:80', id: '575159689BEFB442' }
    # Spotify
    - { keyserver: 'hkp://keyserver.ubuntu.com:80', id: 'BBEBDCB318AD50EC6865090613B00F1FD2C19886' }
    # Google Chrome
    - { keyserver: 'pgp.mit.edu', id: '5044912E' }

- name: PPA - Additional PPA's
  apt_repository: repo={{ item }} state=present
  register: ppastable
  with_items:
    - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ distro }} main
    - deb http://apt.postgresql.org/pub/repos/apt/ {{ distro }}-pgdg main 9.5
    - deb http://archive.canonical.com/ {{ distro }} partner
    - deb http://archive.ubuntu.com/ubuntu {{ distro }} universe
    - deb http://download.fpcomplete.com/ubuntu {{ distro }} main
    - deb http://repository.spotify.com stable non-free
    - deb http://toolbelt.heroku.com/ubuntu ./
    - deb https://deb.nodesource.com/node_5.x {{ distro }} main
    - ppa:ansible/ansible
    - ppa:costales/folder-color
    - ppa:git-core/ppa
    - ppa:hvr/ghc
    - ppa:linrunner/tlp
    - ppa:moorkai/cinnamon
    - ppa:nilarimogard/webupd8
    - ppa:noobslab/icons
    - ppa:noobslab/indicators
    - ppa:noobslab/themes
    - ppa:numix/ppa
    - ppa:ravefinity-project/ppa
    - ppa:webupd8team/java
    - ppa:gwendal-lebihan-dev/cinnamon-nightly
