---
- name: PPA keys - Add keys for repositories
  apt_key: url={{ item }} state=present
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://toolbelt.heroku.com/apt/release.key
    - https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Spotify - check if exists
  stat: path=/usr/bin/spotify
  register: spotify

- name: Spotify - add key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
  when: not spotify.stat.exists

- stat: path=/etc/apt/sources.list.d/google-chrome.list
  register: chrome

- name: Google Chrome - Add to source list
  command: "{{ item }}"
  with_items:
   - apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
   - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  when: not chrome.stat.exists

- stat: path=/etc/apt/sources.list.d/dropbox.list
  register: dropbox

- name: Dropbox - Add to source list
  command: sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ wily main" >> /etc/apt/sources.list.d/dropbox.list'
  when: not dropbox.stat.exists

- name: PPA - Additional PPA's
  apt_repository: repo={{ item }} state=present
  register: ppastable
  with_items:
    - deb http://apt.postgresql.org/pub/repos/apt/ wily-pgdg main 9.5
    - deb http://archive.canonical.com/ wily partner
    - deb http://toolbelt.heroku.com/ubuntu ./
    - deb http://repository.spotify.com stable non-free
    - ppa:ansible/ansible
    - ppa:costales/folder-color
    - ppa:git-core/ppa
    - ppa:linrunner/tlp
    - ppa:noobslab/icons
    - ppa:noobslab/themes
    - ppa:moorkai/cinnamon
    - ppa:numix/ppa
    - ppa:ravefinity-project/ppa
    - ppa:webupd8team/nemo
