---
- name: PPA keys - Add keys for repositories
  apt_key: url={{ item }} state=present
  with_items:
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://toolbelt.heroku.com/apt/release.key
    - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key
    - https://dl.yarnpkg.com/debian/pubkey.gpg
    - "http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_{{ release }}/Release.key"
    - https://download.01.org/gfx/RPM-GPG-KEY-ilg-4
  tags: apt

- name: PPA keys - add with id
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }} state=present
  with_items:
    # Dropbox
    - {
      keyserver: 'pgp.mit.edu',
      id: '5044912E'
    }
    # Haskell
    - {
      keyserver: 'hkp://keyserver.ubuntu.com:80',
      id: '575159689BEFB442'
    }
    # Spotify
    - {
      keyserver: 'hkp://keyserver.ubuntu.com:80',
      id: 'BBEBDCB318AD50EC6865090613B00F1FD2C19886'
    }
    # Docker
    - {
      keyserver: 'hkp://p80.pool.sks-keyservers.net:80',
      id: '58118E89F3A912897C070ADBF76221572C52609D'
    }
    # MariaDB
    - {
      keyserver: 'hkp://keyserver.ubuntu.com:80',
      id: '0xF1656F24C74CD1D8'
    }
  tags: apt

- name: PPA - Additional PPA's
  apt_repository: repo={{ item }} state=present
  register: ppastable
  with_items:
    - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ distro }} main
    - deb http://apt.insynchq.com/ubuntu xenial non-free contrib
    - deb http://archive.canonical.com/ {{ distro }} partner
    - deb http://archive.ubuntu.com/ubuntu {{ distro }} main
    - deb http://archive.ubuntu.com/ubuntu {{ distro }} universe
    - deb http://archive.ubuntu.com/ubuntu {{ distro }} restricted
    - deb http://archive.ubuntu.com/ubuntu {{ distro }} multiverse
    - deb http://download.fpcomplete.com/ubuntu {{ distro }} main
    - "deb http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_{{ release}} /"
    - deb http://repository.spotify.com testing non-free
    - deb http://toolbelt.heroku.com/ubuntu ./
    - deb https://apt.dockerproject.org/repo ubuntu-{{ distro }} main
    - deb https://deb.nodesource.com/node_5.x {{ distro }} main
    # hardcode-tray
    - ppa:andreas-angerer89/sni-qt-patched
    - ppa:duplicity-team/ppa
    - ppa:git-core/ppa
    - ppa:hvr/ghc
    - ppa:linrunner/tlp
    - ppa:nilarimogard/webupd8
    - ppa:webupd8team/terminix
    # Zeal PPA throws an error for some reason
    # - ppa:zeal-developers/ppa
    # Stable cinnamon 3.0
    - ppa:embrosyn/cinnamon
    # Unstable cinnamon - official
    # - ppa:gwendal-lebihan-dev/cinnamon-nightly
    - deb http://dl.yarnpkg.com/debian/ stable main
    - deb [arch=amd64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/{{ mariadb_version }}/ubuntu {{ distro }} main
  tags: apt

