---
- name: PPA keys - Add keys for repositories
  apt_key: url={{ item }} state=present
  with_items:
    - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key
    - https://dl.yarnpkg.com/debian/pubkey.gpg
    - https://download.01.org/gfx/RPM-GPG-KEY-ilg-4
    - https://download.sublimetext.com/sublimehq-pub.gpg
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  tags:
    - apt
    - ppa

- name: PPA keys - add with id
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }} state=present
  with_items:
    # Haskell
    - {
      keyserver: 'hkp://keyserver.ubuntu.com:80',
      id: '575159689BEFB442'
    }
    # Spotify
    - {
      keyserver: 'hkp://keyserver.ubuntu.com:80',
      id: '0DF731E45CE24F27EEEB1450EFDC8610341D9410'
    }
  tags:
    - apt
    - ppa

- name: PPA - Additional PPA's
  apt_repository: repo={{ item }} state=present
  register: ppastable
  with_items:
    - deb http://apt.insynchq.com/ubuntu {{ distro }} non-free contrib
    - deb http://repository.spotify.com stable non-free
    - deb https://download.sublimetext.com/ apt/stable/
    - ppa:duplicity-team/ppa
    - ppa:git-core/ppa
    - ppa:hluk/copyq
    - ppa:papirus/papirus
    - ppa:andreas-angerer89/sni-qt-patched # hardcode-tray
    # Stable cinnamon 3.0
    - ppa:embrosyn/cinnamon
    - deb http://dl.yarnpkg.com/debian/ stable main
    - ppa:phoerious/keepassxc
    - ppa:andreas-angerer89/sni-qt-patched
    - ppa:mikhailnov/pulseeffects
    - https://deb.nodesource.com/{{ node_version }} ubuntu {{ distro }} main
  tags:
    - apt
    - ppa

