---
- name: slack - exists
  stat: path=/usr/bin/slack
  register: slack

- name: Slack - download
  get_url:
    url=https://downloads.slack-edge.com/linux_releases/slack-desktop-2.3.3-amd64.deb
    dest="{{ download_dir }}/slack.deb"
  when: not slack.stat.exists

- name: Slack - install
  apt: deb="{{ download_dir }}/slack.deb"
  when: not slack.stat.exists

