---
- name: Sublime - exists
  stat: path=/usr/bin/subl
  register: sublime

- name: Sublime - download
  become: no
  get_url:
    url=https://download.sublimetext.com/sublime-text_build-3126_amd64.deb
    dest="{{ download_dir }}/sublime_text.deb"
  when: not sublime.stat.exists

- name: Sublime - install
  apt: deb="{{ download_dir }}/sublime_text.deb"
  when: not sublime.stat.exists
