---
- name: Leiningen - exists
  stat: path="{{ home_dir }}/.local/bin/lein"
  register: leiningen

- name: Leiningen - download
  become_user: "{{ user }}"
  get_url:
    url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest="{{ home_dir }}/.local/bin"
    mode=0755
  when: not leiningen.stat.exists

- name: Leiningen - install
  become_user: "{{ user }}"
  command: lein
  when: not leiningen.stat.exists
