---
- name: Dotfiles - Copy dotfiles
  git:
    repo=git@github.com:rpbaptist/dotfiles.git
    dest="{{ home_path }}/.dotfiles"
    update=no
    accept_hostkey=yes

# Replace this script with ansible
# - name: Dotfiles - makesymlinks
#   command: "{{ home_path }}/.dotfiles/bin/makesymlinks.sh"

- name: Oh My Zsh
  git:
    repo=git@github.com:rpbaptist/oh-my-zsh.git
    dest="{{ home_path }}/.oh-my-zsh"
    update=no
    accept_hostkey=yes
